version: '3'
services:
  test_web:
    build:
      context: .
      dockerfile: ./web.docker
    container_name: test_web
    image: test_web
    volumes:
      - ../:/var/www
#      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      -  ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8090:80
    networks:
      - app-network
    links:
      - test_app
  test_app:
    build:
      context: .
      dockerfile: ./app.docker
    container_name: test_app
    image: test_app
    volumes:
      - ../:/var/www
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
    ports:
      - 6001:6001
    links:
      - test_db
  test_db:
    image: mysql:8.0
    container_name: test_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "33071:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
